(function(root,factory){
  var core=(typeof module==='object'&&module.exports)?require('./automation-core.js'):(root&&root.MPCAutomationCore);
  var api=factory(core,root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCAutomation=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(core,root){
  'use strict';
  if(!core)throw new Error('MPCAutomationCore requis');
  function lockToActions(locks){var n=core.normalizeLocks(locks),event={},track={};if(n.gain!=null)event.gain=n.gain;if(n.pitch!=null)event.pitch=n.pitch;['pan','cutoff','sendA','sendB'].forEach(function(k){if(n[k]!=null)track[k]=n[k]});return {event:event,track:track}}
  var ui={pad:null,param:'cutoff',armed:false};
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  function selectedPad(){if(ui.pad)return ui.pad;try{return padId(bank,selectedTrack)}catch(e){return 'A01'}}
  function pIndex(){try{return Math.max(0,Math.min(7,Number(patternIndex)||0))}catch(e){return 0}}
  function selectedStepRef(){var s=root.MPCSequencerV2&&root.MPCSequencerV2.session;if(!s)return null;var p=s.patterns[pIndex()],id=selectedPad(),idx=Math.max(0,Math.min(p.bars*16-1,Number(s.selectedStep)||0));return p.tracks[id]&&p.tracks[id][idx]}
  function applyStepLocks(id,locks,time){var n=core.normalizeLocks(locks);if(root.MPCAudioEngineV2&&root.MPCAudioEngineV2.setStepParams)root.MPCAudioEngineV2.setStepParams(id,n,time);return n}
  function applyAutomationAtStep(id,p,idx,time){if(!p||!p.automation||!root.MPCAudioEngineV2)return;var pos=(Number(idx)||0)/Math.max(1,p.bars*16),vals={};['gain','pan','cutoff','sendA','sendB'].forEach(function(k){var lane=p.automation[id+':'+k],v=core.sampleLane(lane,pos);if(v!=null)vals[k]=v});root.MPCAudioEngineV2.setStepParams(id,vals,time)}
  function paramToValue(param,raw){var v=Number(raw)||0;if(param==='pan')return (v-50)/50;if(param==='pitch')return Math.round((v-50)*48/100);if(param==='gain')return v/100*1.5;return v/100}
  function valueToRaw(param,v){v=Number(v)||0;if(param==='pan')return Math.round((v+1)*50);if(param==='pitch')return Math.round(50+v*100/48);if(param==='gain')return Math.round(v/1.5*100);return Math.round(v*100)}
  function setCurrentLock(){var st=selectedStepRef(),s=root.MPCSequencerV2&&root.MPCSequencerV2.session;if(!st||!s)return;var input=document.getElementById('automationValue'),locks=Object.assign({},st.locks||{});locks[ui.param]=paramToValue(ui.param,input&&input.value);root.MPCSequencerV2.setStepValues(s,pIndex(),selectedPad(),s.selectedStep,{locks:core.normalizeLocks(locks)});renderPanel();if(root.MPCSequencerV2.render)root.MPCSequencerV2.render();try{status('Lock '+ui.param+' · '+selectedPad()+' step '+(s.selectedStep+1))}catch(e){}}
  function clearCurrentLocks(){var st=selectedStepRef(),s=root.MPCSequencerV2&&root.MPCSequencerV2.session;if(!st||!s)return;root.MPCSequencerV2.setStepValues(s,pIndex(),selectedPad(),s.selectedStep,{locks:{}});renderPanel();try{status('Locks du step effacés')}catch(e){}}
  function recordMixerInput(e){if(!ui.armed)return;var inp=e.target&&e.target.closest&&e.target.closest('.mixStrip input[data-k]');if(!inp)return;var param=inp.dataset.k;if(['gain','pan','cutoff','sendA','sendB'].indexOf(param)<0)return;var card=inp.closest('.mixStrip'),id=card&&card.dataset.pad;if(!id)return;var s=root.MPCSequencerV2&&root.MPCSequencerV2.session,ts=root.MPCSequencerV2&&root.MPCSequencerV2.getTransportState&&root.MPCSequencerV2.getTransportState();if(!s||!ts||!ts.playing)return;var p=s.patterns[ts.patternIndex],pos=ts.playIndex/Math.max(1,p.bars*16),value;if(param==='gain')value=Number(inp.value)/100;else if(param==='pan')value=Number(inp.value)/100;else value=Number(inp.value)/100;p.automation=p.automation||{};var key=id+':'+param;p.automation[key]=core.recordPoint(p.automation[key],pos,value);renderPanel()}
  function inject(){var views=document.querySelector('.grooveViews'),wrap=document.getElementById('grooveboxV2');if(!views||!wrap||document.getElementById('grooveAutomationPanel'))return false;var b=document.createElement('button');b.type='button';b.textContent='AUTOMATION';b.dataset.view='automation';views.appendChild(b);var panel=document.createElement('div');panel.id='grooveAutomationPanel';panel.className='grooveAutomationPanel';panel.hidden=true;wrap.appendChild(panel);b.onclick=function(){document.querySelectorAll('.grooveViews button').forEach(function(x){x.classList.toggle('active',x===b)});['grooveGrid','grooveStepEditor','grooveMixerPanel','grooveFxPanel'].forEach(function(id){var e=document.getElementById(id);if(e)e.hidden=true});panel.hidden=false;renderPanel()};views.querySelectorAll('button:not([data-view="automation"])').forEach(function(x){x.addEventListener('click',function(){panel.hidden=true})});document.addEventListener('click',function(e){var step=e.target&&e.target.closest&&e.target.closest('.grooveStep');if(step&&step.dataset.pad){ui.pad=step.dataset.pad;renderPanel()}var pad=e.target&&e.target.closest&&e.target.closest('.pad');if(pad&&pad.dataset.id){ui.pad=pad.dataset.id;renderPanel()}},true);document.addEventListener('input',recordMixerInput,true);renderPanel();return true}
  function renderPanel(){var rootEl=document.getElementById('grooveAutomationPanel');if(!rootEl)return;var st=selectedStepRef(),s=root.MPCSequencerV2&&root.MPCSequencerV2.session,idx=s?Number(s.selectedStep)||0:0,locks=st?core.normalizeLocks(st.locks):{},p=s&&s.patterns[pIndex()],lanes=p&&p.automation?Object.keys(p.automation).filter(function(k){return k.indexOf(selectedPad()+':')===0&&p.automation[k]&&p.automation[k].length}).length:0,current=locks[ui.param]==null?({gain:1,pan:0,pitch:0,cutoff:1,sendA:0,sendB:0}[ui.param]):locks[ui.param];rootEl.innerHTML='<div class="automationHead"><div><small>AUTOMATION / PARAM LOCK</small><b>'+selectedPad()+' · STEP '+(idx+1)+'</b></div><span>'+Object.keys(locks).length+' LOCK(S) · '+lanes+' LANE(S)</span></div><div class="automationControls"><label>PARAMÈTRE<select id="automationParam"><option value="gain">GAIN</option><option value="pan">PAN</option><option value="pitch">PITCH</option><option value="cutoff">FILTER</option><option value="sendA">SEND A</option><option value="sendB">SEND B</option></select></label><label>VALEUR<input id="automationValue" type="range" min="0" max="100" value="'+valueToRaw(ui.param,current)+'"><output id="automationValueOut">'+String(current)+'</output></label><button id="automationLock">LOCK STEP</button><button id="automationClear">EFFACER LOCKS</button><button id="automationArm" class="'+(ui.armed?'active':'')+'">● AUTO REC</button><button id="automationClearLane">VIDER LANE</button></div>';var sel=document.getElementById('automationParam');if(sel){sel.value=ui.param;sel.onchange=function(){ui.param=this.value;renderPanel()}}var val=document.getElementById('automationValue');if(val)val.oninput=function(){var o=document.getElementById('automationValueOut');if(o)o.textContent=String(paramToValue(ui.param,this.value))};document.getElementById('automationLock').onclick=setCurrentLock;document.getElementById('automationClear').onclick=clearCurrentLocks;document.getElementById('automationArm').onclick=function(){ui.armed=!ui.armed;renderPanel();try{status(ui.armed?'Automation armée':'Automation désarmée')}catch(e){}};document.getElementById('automationClearLane').onclick=function(){if(!p)return;p.automation=p.automation||{};delete p.automation[selectedPad()+':'+ui.param];renderPanel()}}
  function init(){var n=0,t=setInterval(function(){n++;if(inject()||n>100)clearInterval(t)},50)}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {lockToActions:lockToActions,applyStepLocks:applyStepLocks,applyAutomationAtStep:applyAutomationAtStep,render:renderPanel};
});
