(function(root,factory){
  var seq=(typeof module==='object'&&module.exports)?require('./sequencer-core.js'):(root&&root.MPCSequencerCore);
  var mix=(typeof module==='object'&&module.exports)?require('./mixer-core.js'):(root&&root.MPCMixerCore);
  var fx=(typeof module==='object'&&module.exports)?require('./fx-rack.js'):(root&&root.MPCFXRack);
  var api=factory(seq,mix,fx,root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCExportV2=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(seq,mix,fx,root){
  'use strict';
  function clamp(v,a,b){v=Number(v);if(!Number.isFinite(v))v=a;return Math.min(b,Math.max(a,v))}
  function patternDurationSeconds(pattern,bpm){var bars=Math.max(1,Math.min(8,Number(pattern&&pattern.bars)||1));return 60/clamp(bpm||120,40,300)*4*bars}
  function safeFilename(name){var s=String(name||'').replace(/[\\/:*?"<>|]+/g,' ').replace(/\s+/g,' ').trim().slice(0,80);return s||'track'}
  function audibleTrackIds(pattern,mixer){var ids=Object.keys((pattern&&pattern.tracks)||{}).filter(function(id){return (pattern.tracks[id]||[]).some(function(s){return s&&s.on})}),anySolo=ids.some(function(id){return !!(mixer&&mixer[id]&&mixer[id].solo)});return ids.filter(function(id){var s=(mixer&&mixer[id])||{};return !s.muted&&(!anySolo||s.solo)})}
  function eventSchedule(pattern,bpm,ids,swingAmount){var sd=60/clamp(bpm||120,40,300)/4,out=[],tracks=(pattern&&pattern.tracks)||{},list=ids||Object.keys(tracks),amount=clamp(swingAmount==null?((pattern&&pattern.swing&&pattern.swing.amount)||0):swingAmount,0,.7),lane=(pattern&&pattern.swing&&pattern.swing.lane)||'offbeat';list.forEach(function(id){(tracks[id]||[]).forEach(function(step,i){var base=i*sd,events=seq.expandStepEvents({step:step,stepIndex:i,baseTime:base,safeTime:0,stepDuration:sd,swing:amount,swingLane:lane,cycleSeed:'export',seedKey:id});events.forEach(function(e){out.push({padId:id,time:e.time,velocity:e.velocity,pitch:e.pitch+(Number(e.locks&&e.locks.pitch)||0),locks:e.locks||{},accent:e.accent,ratchetIndex:e.ratchetIndex})})})});out.sort(function(a,b){return a.time-b.time||a.padId.localeCompare(b.padId)});return out}
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  function cutoffHz(n){n=clamp(n,0,1);return 80*Math.pow(250,n)}
  function buildTrack(ctx,rack,state){state=mix.normalizeMixerState(state);var input=ctx.createGain(),low=ctx.createBiquadFilter(),mid=ctx.createBiquadFilter(),high=ctx.createBiquadFilter(),filter=ctx.createBiquadFilter(),pan=ctx.createStereoPanner(),dry=ctx.createGain(),sendA=ctx.createGain(),sendB=ctx.createGain();low.type='lowshelf';low.frequency.value=180;low.gain.value=state.eqLow;mid.type='peaking';mid.frequency.value=1000;mid.Q.value=.8;mid.gain.value=state.eqMid;high.type='highshelf';high.frequency.value=6500;high.gain.value=state.eqHigh;filter.type='lowpass';filter.frequency.value=cutoffHz(state.cutoff);filter.Q.value=state.resonance;pan.pan.value=state.pan;dry.gain.value=1;sendA.gain.value=state.sendA;sendB.gain.value=state.sendB;input.connect(low);low.connect(mid);mid.connect(high);high.connect(filter);filter.connect(pan);pan.connect(dry);dry.connect(rack.getInput());pan.connect(sendA);sendA.connect(rack.getSendAInput());pan.connect(sendB);sendB.connect(rack.getSendBInput());return {input:input,pan:pan,filter:filter,dry:dry,sendA:sendA,sendB:sendB}}
  function applyLocks(nodes,locks,time){locks=locks||{};try{if(locks.gain!=null)nodes.dry.gain.setValueAtTime(clamp(locks.gain,0,1.5),time);if(locks.pan!=null)nodes.pan.pan.setValueAtTime(clamp(locks.pan,-1,1),time);if(locks.cutoff!=null)nodes.filter.frequency.setValueAtTime(cutoffHz(locks.cutoff),time);if(locks.sendA!=null)nodes.sendA.gain.setValueAtTime(clamp(locks.sendA,0,1),time);if(locks.sendB!=null)nodes.sendB.gain.setValueAtTime(clamp(locks.sendB,0,1),time)}catch(e){}}
  function appState(){var session=root.MPCSequencerV2&&root.MPCSequencerV2.session;if(!session)throw new Error('Séquenceur V2 indisponible');var pi=0;try{pi=Number(patternIndex)||0}catch(e){}var bpm=Number(document.getElementById('bpm').value)||120,mixer=(root.MPCAudioEngineV2&&root.MPCAudioEngineV2.snapshot)?root.MPCAudioEngineV2.snapshot():{mixer:{},fxRack:{}};return {session:session,pattern:session.patterns[pi],patternIndex:pi,bpm:bpm,mixer:mixer.mixer||{},fxRack:mixer.fxRack||{},master:(Number(document.getElementById('master').value)||82)/100,name:document.getElementById('projectName').value||'MPC'}}
  async function renderTracks(ids,options){options=options||{};var st=options.state||appState(),pattern=options.pattern||st.pattern,bpm=options.bpm||st.bpm,duration=patternDurationSeconds(pattern,bpm)+1.2,sampleRate=44100;try{ensureAudio();sampleRate=audioCtx.sampleRate||44100}catch(e){}var off=new OfflineAudioContext(2,Math.ceil(sampleRate*duration),sampleRate),master=off.createGain();master.gain.value=st.master==null?.82:st.master;master.connect(off.destination);var rack=fx.create(off,master,st.fxRack);rack.setBpm(bpm);var chains={};ids.forEach(function(id){chains[id]=buildTrack(off,rack,st.mixer[id])});var events=eventSchedule(pattern,bpm,ids,clamp((Number(document.getElementById('swing')&&document.getElementById('swing').value)||0)/100,0,.7));events.forEach(function(ev){var p=pads[ev.padId],nodes=chains[ev.padId];if(!p||!nodes)return;applyLocks(nodes,ev.locks,ev.time);var vol=ev.velocity*(Number(p.gain)||1),pitch=(Number(p.pitch)||0)+ev.pitch;if(p.sample&&p.sample.kind==='factory')scheduleFactory(FACTORY[p.sample.factoryIndex],off,nodes.input,ev.time,vol,pitch);else if(p.buffer)scheduleUser(Object.assign({},p,{pitch:pitch,loop:false}),off,nodes.input,ev.time,vol)});return await off.startRendering()}
  function downloadWav(buffer,name){var bytes=audioBufferToWav(buffer),blob=new Blob([bytes],{type:'audio/wav'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=safeFilename(name)+'.wav';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},5000)}
  async function renderMaster(options){var st=(options&&options.state)||appState(),ids=audibleTrackIds(st.pattern,st.mixer);var rendered=await renderTracks(ids,Object.assign({},options,{state:st}));return rendered}
  async function renderStem(padId,options){var st=(options&&options.state)||appState();return await renderTracks([padId],Object.assign({},options,{state:st}))}
  async function renderAllStems(){var st=appState(),ids=audibleTrackIds(st.pattern,st.mixer);if(!ids.length){status('Aucune piste audible à exporter');return}for(var i=0;i<ids.length;i++){var id=ids[i];status('Export stems '+(i+1)+'/'+ids.length+' · '+id);var buf=await renderStem(id,{state:st}),name=st.name+'-'+id+'-'+(pads[id]&&pads[id].name||'track');downloadWav(buf,name);await new Promise(function(r){setTimeout(r,220)})}status(ids.length+' stems WAV exportés')}
  async function exportMaster(){try{status('Rendu master V2…');var st=appState(),buf=await renderMaster({state:st});downloadWav(buf,st.name+'-master');status('Master WAV V2 exporté')}catch(e){status('Export V2 : '+e.message)}}
  function inject(){var btn=document.getElementById('exportWavBtn');if(btn)btn.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();exportMaster()},true);var bottom=document.querySelector('.bottom');if(bottom&&!document.getElementById('exportStemsBtn')){var b=document.createElement('button');b.id='exportStemsBtn';b.textContent='EXPORT STEMS';b.onclick=function(){renderAllStems().catch(function(e){status('Stems : '+e.message)})};bottom.appendChild(b)}return true}
  function init(){inject()}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {patternDurationSeconds:patternDurationSeconds,safeFilename:safeFilename,audibleTrackIds:audibleTrackIds,eventSchedule:eventSchedule,renderMaster:renderMaster,renderStem:renderStem,renderAllStems:renderAllStems};
});
