(function(root,factory){
  var core=(typeof module==='object'&&module.exports)?require('./midi-core.js'):(root&&root.MPCMIDI);
  var api=factory(core,root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCMIDIController=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(core,root){
  'use strict';
  function normalizeMidiMessage(data){
    if(!data||data.length<3)return null;var status=Number(data[0])||0,type=status&0xf0,channel=status&0x0f,number=Number(data[1])&0x7f,value=Number(data[2])&0x7f;
    if(type===0x90)return {type:'note',channel:channel,number:number,value:value,normalized:value/127,on:value>0};
    if(type===0x80)return {type:'note',channel:channel,number:number,value:value,normalized:value/127,on:false};
    if(type===0xB0)return {type:'cc',channel:channel,number:number,value:value,normalized:value/127,on:true};
    return null;
  }
  function key(m){return m&&[m.type,m.channel,m.number].join(':')}
  function learnMapping(map,target,message){
    var m=message&&message.type?message:normalizeMidiMessage(message),out=Object.assign({},map||{});if(!m||!target)return out;var sig=key(m);Object.keys(out).forEach(function(k){if(k!==target&&key(out[k])===sig)delete out[k]});out[target]={type:m.type,channel:m.channel,number:m.number};return out;
  }
  function findMappingTarget(map,message){var m=message&&message.type?message:normalizeMidiMessage(message);if(!m)return null;var sig=key(m),found=null;Object.keys(map||{}).some(function(k){if(key(map[k])===sig){found=k;return true}return false});return found}
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  var state={access:null,inputs:new Map(),mappings:{},learning:null,supported:false};
  function load(){try{state.mappings=JSON.parse(localStorage.getItem('mpc-midi-mappings')||'{}')||{}}catch(e){state.mappings={}}}
  function save(){try{localStorage.setItem('mpc-midi-mappings',JSON.stringify(state.mappings))}catch(e){}}
  function statusText(t){try{status(t)}catch(e){var n=document.getElementById('status');if(n)n.textContent=t}}
  function targetLabel(t){if(!t)return 'AUCUN';if(t.indexOf('pad:')===0)return t.slice(4);var p=t.split(':');return p[0]==='mixer'?(p[1]+' '+p[2].toUpperCase()):t}
  function applyMapped(target,msg){
    if(target.indexOf('pad:')===0){if(msg.type==='note'&&msg.on){var id=target.slice(4);try{playPad(id,null,null,msg.normalized||1)}catch(e){}}return}
    var p=target.split(':');if(p[0]==='mixer'&&p.length===3&&msg.type==='cc'&&root.MPCAudioEngineV2){var id=p[1],param=p[2],v=msg.normalized,next={};if(param==='pan')next.pan=v*2-1;else if(param==='gain'){try{pads[id].gain=v*1.5}catch(e){}}else if(param==='cutoff'||param==='sendA'||param==='sendB')next[param]=v;if(Object.keys(next).length)root.MPCAudioEngineV2.setTrackState(id,next);root.MPCAudioEngineV2.renderMixer&&root.MPCAudioEngineV2.renderMixer()}
  }
  function onMidi(e){var msg=normalizeMidiMessage(e.data);if(!msg)return;if(state.learning){state.mappings=learnMapping(state.mappings,state.learning,msg);var done=state.learning;state.learning=null;save();renderPanel();statusText('MIDI Learn : '+targetLabel(done)+' assigné');return}var target=findMappingTarget(state.mappings,msg);if(target)applyMapped(target,msg)}
  function bindInputs(){if(!state.access)return;var live=new Set();state.access.inputs.forEach(function(input){live.add(input.id);if(!state.inputs.has(input.id)){input.onmidimessage=onMidi;state.inputs.set(input.id,input)}});state.inputs.forEach(function(input,id){if(!live.has(id)){try{input.onmidimessage=null}catch(e){}state.inputs.delete(id)}});renderPanel()}
  async function requestAccess(){if(!navigator.requestMIDIAccess){state.supported=false;renderPanel();return null}try{state.access=await navigator.requestMIDIAccess({sysex:false});state.supported=true;state.access.onstatechange=bindInputs;bindInputs();statusText('MIDI connecté · '+state.inputs.size+' entrée(s)');return state.access}catch(e){state.supported=false;renderPanel();statusText('MIDI refusé ou indisponible');return null}}
  function learn(target){state.learning=target;renderPanel();statusText('MIDI Learn armé · bouge maintenant ton contrôleur');return target}
  function clearMapping(target){delete state.mappings[target];save();renderPanel()}
  function filename(base,suffix){return String(base||'mpc').replace(/[\\/:*?"<>|]+/g,' ').trim().slice(0,60)+'-'+suffix+'.mid'}
  function download(bytes,name){var blob=core.toDownloadBlob(bytes),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},4000)}
  function currentSession(){return root.MPCSequencerV2&&root.MPCSequencerV2.session}
  function exportPattern(){var s=currentSession();if(!s)return statusText('Séquenceur V2 indisponible');var pi=0;try{pi=Number(patternIndex)||0}catch(e){}var bpm=Number(document.getElementById('bpm').value)||120,name=document.getElementById('projectName').value||'mpc';download(core.encodePattern({pattern:s.patterns[pi],bpm:bpm}),filename(name,'pattern-'+(pi+1)));statusText('MIDI pattern exporté')}
  function exportSong(){var s=currentSession();if(!s)return statusText('Séquenceur V2 indisponible');var bpm=Number(document.getElementById('bpm').value)||120,name=document.getElementById('projectName').value||'mpc',arr=(s.songArrangement&&s.songArrangement.length)?s.songArrangement:s.patterns.map(function(_,i){return {patternIndex:i,repeats:1}});download(core.encodeSong({patterns:s.patterns,arrangement:arr,bpm:bpm}),filename(name,'song'));statusText('MIDI chanson exporté')}
  function inject(){var wrap=document.getElementById('grooveboxV2'),views=wrap&&wrap.querySelector('.grooveViews');if(!wrap||!views||document.getElementById('grooveMidiPanel'))return false;var b=document.createElement('button');b.type='button';b.textContent='MIDI';b.dataset.view='midi';views.appendChild(b);var p=document.createElement('div');p.id='grooveMidiPanel';p.className='grooveMidiPanel';p.hidden=true;wrap.appendChild(p);b.onclick=function(){document.querySelectorAll('.grooveViews button').forEach(function(x){x.classList.toggle('active',x===b)});['grooveGrid','grooveStepEditor','grooveMixerPanel','grooveFxPanel','grooveAutomationPanel'].forEach(function(id){var e=document.getElementById(id);if(e)e.hidden=true});p.hidden=false;renderPanel()};views.querySelectorAll('button:not([data-view="midi"])').forEach(function(x){x.addEventListener('click',function(){p.hidden=true})});renderPanel();return true}
  function renderPanel(){var p=document.getElementById('grooveMidiPanel');if(!p)return;var selected='A01';try{selected=selectedPad}catch(e){}var padTarget='pad:'+selected,panTarget='mixer:'+selected+':pan',cutTarget='mixer:'+selected+':cutoff',label=function(t){var m=state.mappings[t];return m?(m.type.toUpperCase()+' CH'+(m.channel+1)+' #'+m.number):'NON ASSIGNÉ'};p.innerHTML='<div class="midiHead"><div><small>WEB MIDI</small><b>'+ (state.supported?'MIDI PRÊT':('requestMIDIAccess' in navigator?'MIDI NON CONNECTÉ':'MIDI NON DISPONIBLE'))+'</b></div><span>'+state.inputs.size+' ENTRÉE(S)</span></div><div class="midiActions"><button id="midiConnect">CONNECTER MIDI</button><button id="midiPatternExport">EXPORT PATTERN MIDI</button><button id="midiSongExport">EXPORT SONG MIDI</button></div><div class="midiLearnGrid"><article><b>'+selected+' PAD</b><small>'+label(padTarget)+'</small><button data-learn="'+padTarget+'">LEARN</button><button data-clear="'+padTarget+'">EFFACER</button></article><article><b>'+selected+' PAN</b><small>'+label(panTarget)+'</small><button data-learn="'+panTarget+'">LEARN</button><button data-clear="'+panTarget+'">EFFACER</button></article><article><b>'+selected+' FILTER</b><small>'+label(cutTarget)+'</small><button data-learn="'+cutTarget+'">LEARN</button><button data-clear="'+cutTarget+'">EFFACER</button></article></div><div class="midiLearning">'+(state.learning?'EN ATTENTE : '+targetLabel(state.learning):'MIDI Learn désarmé')+'</div>';document.getElementById('midiConnect').onclick=requestAccess;document.getElementById('midiPatternExport').onclick=exportPattern;document.getElementById('midiSongExport').onclick=exportSong;p.querySelectorAll('[data-learn]').forEach(function(x){x.onclick=function(){learn(this.dataset.learn)}});p.querySelectorAll('[data-clear]').forEach(function(x){x.onclick=function(){clearMapping(this.dataset.clear)}})}
  function init(){load();state.supported=!!navigator.requestMIDIAccess;var n=0,t=setInterval(function(){n++;if(inject()||n>100)clearInterval(t)},50)}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {normalizeMidiMessage:normalizeMidiMessage,learnMapping:learnMapping,findMappingTarget:findMappingTarget,requestAccess:requestAccess,learn:learn,clearMapping:clearMapping,exportPattern:exportPattern,exportSong:exportSong,get mappings(){return Object.assign({},state.mappings)}};
});
