(function(root,factory){
  var core=(typeof module==='object'&&module.exports)?require('./sonilo-core.js'):(root&&root.MPCSoniloCore);
  var api=factory(core,root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCSonilo=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(core,root){
  'use strict';
  function errorMessage(code){var map={auth_required:'Connexion Supabase requise avant d’utiliser Sonilo.',sonilo_not_configured:'Le secret SONILO_API_KEY n’est pas configuré dans Supabase.',auth_invalid:'La clé Sonilo serveur est invalide ou a été révoquée.',insufficient_balance:'Solde/crédits Sonilo insuffisants pour cette génération.',forbidden:'Le compte Sonilo n’a pas accès à ce service.',rate_limited:'Trop de requêtes Sonilo. Réessaie dans quelques secondes.',invalid_request:'Paramètres Sonilo invalides.',invalid_type:'Type de génération invalide.',invalid_prompt:'Prompt Sonilo invalide.',invalid_duration:'Durée Sonilo invalide.',invalid_format:'Format Sonilo invalide.',upstream_unreachable:'Service Sonilo momentanément inaccessible.',upstream_error:'Erreur du service Sonilo.',not_found:'Tâche Sonilo introuvable.',generation_failed:'La génération Sonilo a échoué.'};return map[code]||'Erreur Sonilo.'}
  function pollDelay(retryAfter){var n=Number(retryAfter);return Number.isFinite(n)&&n>0?Math.min(15000,Math.max(2000,n*1000)):3000}
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  var state={busy:false,taskId:null,last:null,polling:false};
  function statusText(t){try{status(t)}catch(e){var n=document.getElementById('status');if(n)n.textContent=t}}
  function currentClient(){try{return sb}catch(e){return null}}
  function currentUser(){try{return sbUser}catch(e){return null}}
  function selectedPadId(){try{return selectedPad}catch(e){return 'A01'}}
  async function invoke(name,body){var client=currentClient();if(!client)throw Object.assign(new Error('Supabase non configuré'),{code:'auth_required'});var result=await client.functions.invoke(name,{body:body});if(result.error){var code='upstream_error',ctx=result.error.context;try{if(ctx&&typeof ctx.json==='function'){var d=await ctx.clone().json();code=d&&d.error&&d.error.code||code}}catch(e){}throw Object.assign(new Error(errorMessage(code)),{code:code})}if(result.data&&result.data.error)throw Object.assign(new Error(errorMessage(result.data.error.code)),{code:result.data.error.code,retryAfter:result.data.error.retryAfter});return result.data}
  async function importAudioResult(task){if(!task||!task.audio||!/^https:\/\//.test(task.audio.url))throw Object.assign(new Error('Aucun audio Sonilo sécurisé reçu'),{code:'generation_failed'});var response=await fetch(task.audio.url,{mode:'cors'});if(!response.ok)throw new Error('Téléchargement audio HTTP '+response.status);var blob=await response.blob(),buffer=await decodeBlob(blob),id=selectedPadId(),p=pads[id];if(!p)throw new Error('Pad sélectionné introuvable');var ext=(task.audio.contentType||blob.type||'').includes('wav')?'wav':(task.audio.contentType||blob.type||'').includes('mpeg')?'mp3':(task.audio.contentType||blob.type||'').includes('mp4')?'m4a':'audio';p.buffer=buffer;p.userBlob=new File([blob],'Sonilo-'+Date.now()+'.'+ext,{type:blob.type||task.audio.contentType||'audio/mpeg'});p.sample={kind:'user'};p.name=(task.type==='text_to_sfx'?'Sonilo SFX':'Sonilo Music')+' '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});p.cloudPath=null;p.start=0;p.end=1;p.pitch=0;p.externalMeta={provider:'Sonilo',taskId:task.taskId,generated:true};renderPads();renderEditor();renderTrackSelect();statusText('Sonilo importé sur '+id);return id}
  async function pollTask(taskId){state.polling=true;for(var i=0;i<60&&state.polling;i++){var data=await invoke('sonilo-task',{taskId:taskId}),task=core.normalizeTaskResponse(data);state.last=task;renderState();if(task.status==='succeeded'||task.status==='completed'){state.polling=false;await importAudioResult(task);return task}if(task.status==='failed'||task.status==='canceled'){state.polling=false;throw Object.assign(new Error(task.error||errorMessage('generation_failed')),{code:'generation_failed'})}await new Promise(function(r){setTimeout(r,pollDelay(task.retryAfter))})}state.polling=false;throw new Error('La tâche Sonilo continue en arrière-plan. Relance la vérification plus tard.')}
  async function generate(){if(state.busy)return;if(!currentUser()){statusText(errorMessage('auth_required'));renderState(errorMessage('auth_required'));return}var type=document.getElementById('soniloType').value,prompt=document.getElementById('soniloPrompt').value,duration=Number(document.getElementById('soniloDuration').value),format=document.getElementById('soniloFormat').value,req;try{req=core.normalizeGenerateRequest({type:type,prompt:prompt,duration:duration,format:format})}catch(e){renderState(e.message);statusText(e.message);return}state.busy=true;renderState('Envoi vers Sonilo…');try{var data=await invoke('sonilo-generate',req);state.taskId=String(data.taskId||'');if(!state.taskId)throw new Error('Sonilo n’a pas retourné de tâche');renderState('Génération Sonilo en cours…');await pollTask(state.taskId)}catch(e){state.polling=false;renderState(e.message||errorMessage(e.code));statusText(e.message||errorMessage(e.code))}finally{state.busy=false;renderState()}}
  function stopPolling(){state.polling=false;renderState('Vérification arrêtée. La génération serveur peut continuer.')}
  function syncType(){var t=document.getElementById('soniloType'),d=document.getElementById('soniloDuration'),f=document.getElementById('soniloFormat');if(!t||!d||!f)return;if(t.value==='music'){d.min='5';d.max='360';if(Number(d.value)<5)d.value='30';f.innerHTML='<option value="m4a">M4A</option><option value="wav">WAV</option><option value="mp3">MP3</option>'}else{d.min='.5';d.max='180';if(Number(d.value)>180||Number(d.value)<.5)d.value='8';f.innerHTML='<option value="aac">AAC</option><option value="wav">WAV</option><option value="mp3">MP3</option><option value="flac">FLAC</option>'}}
  function renderState(message){var out=document.getElementById('soniloState'),go=document.getElementById('soniloGenerate'),stop=document.getElementById('soniloStopPoll');if(out){var text=message||state.last&&('Tâche '+state.last.status)||state.taskId&&('Tâche '+state.taskId)||'Prêt';out.textContent=text}if(go){go.disabled=state.busy||state.polling;go.textContent=state.busy||state.polling?'GÉNÉRATION EN COURS…':'GÉNÉRER ET IMPORTER'}if(stop)stop.hidden=!state.polling}
  function ensureDialog(){var d=document.getElementById('soniloDialog');if(d)return d;d=document.createElement('dialog');d.id='soniloDialog';d.innerHTML='<div class="soniloCard"><div class="dialogHead"><div><small>SONILO AI</small><h2>Créer un son pour ton pad</h2></div><button id="soniloClose" type="button">✕</button></div><p>La génération passe par une Edge Function Supabase. La clé Sonilo reste côté serveur et n’est jamais envoyée au navigateur.</p><label>TYPE<select id="soniloType"><option value="sfx">SFX / ONE-SHOT</option><option value="music">MUSIQUE / LOOP</option></select></label><label>PROMPT<textarea id="soniloPrompt" maxlength="2000" rows="4" placeholder="Ex. darbuka raï sèche, guellal percutant, attaque nette…"></textarea></label><div class="soniloRow"><label>DURÉE (s)<input id="soniloDuration" type="number" min=".5" max="180" step=".5" value="8"></label><label>FORMAT<select id="soniloFormat"></select></label></div><button id="soniloGenerate" class="soniloPrimary" type="button">GÉNÉRER ET IMPORTER</button><button id="soniloStopPoll" type="button" hidden>ARRÊTER LA VÉRIFICATION</button><div id="soniloState" class="soniloState">Prêt</div><small class="soniloHint">Le pad n’est remplacé qu’après téléchargement et décodage audio réussis.</small></div>';document.body.appendChild(d);document.getElementById('soniloClose').onclick=function(){if(!state.busy)d.close()};document.getElementById('soniloType').onchange=syncType;document.getElementById('soniloGenerate').onclick=generate;document.getElementById('soniloStopPoll').onclick=stopPolling;syncType();return d}
  function open(){var d=ensureDialog();renderState();if(!d.open)d.showModal()}
  function inject(){var grid=document.querySelector('.creationGrid');if(grid&&!document.getElementById('soniloOpenBtn')){var b=document.createElement('button');b.id='soniloOpenBtn';b.type='button';b.textContent='🤖 SONILO AI';b.onclick=open;grid.appendChild(b)}var bottom=document.querySelector('.bottom');if(bottom&&!document.getElementById('soniloBottomBtn')){var bb=document.createElement('button');bb.id='soniloBottomBtn';bb.type='button';bb.textContent='SONILO AI';bb.onclick=open;bottom.appendChild(bb)}return !!(grid||bottom)}
  function init(){var n=0,t=setInterval(function(){n++;if(inject()||n>100)clearInterval(t)},50)}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {errorMessage:errorMessage,pollDelay:pollDelay,open:open,generate:generate,stopPolling:stopPolling};
});
