(function(root,factory){
  var api=factory(root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCVSTBridge=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  'use strict';
  function normalizeBridgeUrl(value){var u;try{u=new URL(String(value||'').trim())}catch(e){throw new Error('Adresse VST locale invalide')}if(u.protocol!=='http:')throw new Error('Adresse VST locale HTTP requise');var h=u.hostname.toLowerCase(),local=h==='localhost'||h==='127.0.0.1'||/^10\./.test(h)||/^192\.168\./.test(h)||(/^172\.(\d+)\./.test(h)&&(()=>{var n=Number(h.split('.')[1]);return n>=16&&n<=31})());if(!local)throw new Error('Adresse VST locale/LAN requise');return u.origin}
  function safePluginId(id){id=String(id||'');return /^vst_[A-Za-z0-9]{6,64}$/.test(id)?id:null}
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  var state={url:'http://127.0.0.1:8766',pin:'',plugins:[],selected:'',busy:false};
  function load(){try{var x=JSON.parse(localStorage.getItem('mpc-vst-bridge')||'{}');if(x.url)state.url=normalizeBridgeUrl(x.url);state.pin=String(x.pin||'')}catch(e){}}
  function save(){try{localStorage.setItem('mpc-vst-bridge',JSON.stringify({url:state.url,pin:state.pin}))}catch(e){}}
  function statusText(t){try{status(t)}catch(e){var n=document.getElementById('status');if(n)n.textContent=t}}
  async function request(path,options){var url=normalizeBridgeUrl(state.url)+path,opt=Object.assign({},options||{});opt.headers=Object.assign({},opt.headers||{},state.pin?{'X-MPC-PIN':state.pin}:{});var r=await fetch(url,opt);var ct=r.headers.get('content-type')||'';if(!r.ok){var msg='HTTP '+r.status;try{if(ct.includes('json')){var d=await r.json();msg=d.error||msg}}catch(e){}throw new Error(msg)}return r}
  async function refresh(){state.url=normalizeBridgeUrl(document.getElementById('vstBridgeUrl').value);state.pin=document.getElementById('vstBridgePin').value.trim();save();state.busy=true;render();try{var r=await request('/api/vst/plugins'),d=await r.json();state.plugins=Array.isArray(d.plugins)?d.plugins:[];if(!state.plugins.some(function(p){return p.id===state.selected}))state.selected=state.plugins[0]&&state.plugins[0].id||'';render();statusText(state.plugins.length+' VST3 détecté(s) sur le PC')}catch(e){state.plugins=[];render(e.message);statusText('VST Bridge : '+e.message)}finally{state.busy=false;render()}}
  async function processSelected(){if(state.busy)return;var id=safePluginId(state.selected);if(!id)return statusText('Sélectionne un VST3');var p;try{p=selected();await ensureEditableSample(p)}catch(e){return statusText('VST : '+e.message)}state.busy=true;render('Traitement VST3 en cours…');try{var wav=new Blob([audioBufferToWav(p.buffer)],{type:'audio/wav'}),name=encodeURIComponent((p.name||p.id)+'.wav'),r=await request('/api/vst/process?plugin='+encodeURIComponent(id)+'&filename='+name,{method:'POST',headers:{'Content-Type':'audio/wav'},body:wav}),blob=await r.blob(),buffer=await decodeBlob(blob);p.buffer=buffer;p.userBlob=new File([blob],(p.name||'sample')+'-VST.wav',{type:'audio/wav'});p.sample={kind:'user'};p.start=0;p.end=1;p.cloudPath=null;p.externalMeta=Object.assign({},p.externalMeta||{},{provider:'VST Bridge',pluginId:id,processed:true});renderEditor();renderPads();statusText('VST3 appliqué sur '+p.id)}catch(e){statusText('VST : '+e.message);render(e.message)}finally{state.busy=false;render()}}
  function ensureDialog(){var d=document.getElementById('vstDialog');if(d)return d;d=document.createElement('dialog');d.id='vstDialog';d.innerHTML='<div class="vstCard"><div class="dialogHead"><div><small>VST3 PC BRIDGE</small><h2>Plugins Windows sur MPC Studio</h2></div><button id="vstClose" type="button">✕</button></div><p>Les VST3 restent installés et exécutés sur ton PC. MPC Studio envoie uniquement le sample WAV au pont local puis récupère le WAV traité.</p><label>ADRESSE DU PC<input id="vstBridgeUrl" value="http://127.0.0.1:8766"></label><label>PIN DU PONT<input id="vstBridgePin" inputmode="numeric" maxlength="12"></label><button id="vstRefresh" type="button">DÉTECTER LES VST3</button><label>PLUGIN<select id="vstPlugin"></select></label><button id="vstProcess" class="vstPrimary" type="button">APPLIQUER AU PAD SÉLECTIONNÉ</button><div id="vstState" class="vstState">Pont PC non connecté</div><small>Le fichier MPluginManager sert à installer/gérer les plugins MeldaProduction sur Windows ; il n’est pas exécuté par la PWA.</small></div>';document.body.appendChild(d);document.getElementById('vstClose').onclick=function(){if(!state.busy)d.close()};document.getElementById('vstRefresh').onclick=refresh;document.getElementById('vstProcess').onclick=processSelected;document.getElementById('vstPlugin').onchange=function(){state.selected=this.value};return d}
  function render(message){if(!canUseBrowser())return;var d=document.getElementById('vstDialog');if(!d)return;var url=document.getElementById('vstBridgeUrl'),pin=document.getElementById('vstBridgePin'),sel=document.getElementById('vstPlugin'),go=document.getElementById('vstProcess'),out=document.getElementById('vstState');if(url&&document.activeElement!==url)url.value=state.url;if(pin&&document.activeElement!==pin)pin.value=state.pin;if(sel){sel.innerHTML='';state.plugins.forEach(function(p){sel.add(new Option((p.name||p.id)+(p.vendor?' · '+p.vendor:''),p.id))});sel.value=state.selected}if(go)go.disabled=state.busy||!state.selected;if(out)out.textContent=message||(state.busy?'Traitement…':state.plugins.length?(state.plugins.length+' plugin(s) prêt(s)'):'Pont PC non connecté')}
  function open(){var d=ensureDialog();render();if(!d.open)d.showModal()}
  function inject(){var g=document.querySelector('.creationGrid');if(g&&!document.getElementById('vstOpenBtn')){var b=document.createElement('button');b.id='vstOpenBtn';b.type='button';b.textContent='🎛 VST3 PC';b.onclick=open;g.appendChild(b)}return !!g}
  function init(){load();var n=0,t=setInterval(function(){n++;if(inject()||n>100)clearInterval(t)},50)}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {normalizeBridgeUrl:normalizeBridgeUrl,safePluginId:safePluginId,open:open,refresh:refresh,processSelected:processSelected};
});
