(function(root,factory){
  var api=factory(root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.MPCVSTBridge=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  'use strict';
  function isPrivateHost(host){host=String(host||'').toLowerCase();if(host==='localhost'||host==='127.0.0.1')return true;if(/^10\./.test(host)||/^192\.168\./.test(host))return true;var m=host.match(/^172\.(\d+)\./);return !!(m&&Number(m[1])>=16&&Number(m[1])<=31)}
  function normalizeBridgeUrl(value){var u;try{u=new URL(String(value||'').trim())}catch(e){throw new Error('Adresse VST locale invalide')}if(!['http:','https:'].includes(u.protocol)||!isPrivateHost(u.hostname))throw new Error('Adresse VST locale/LAN HTTP(S) requise');return u.origin}
  function bridgeRequestPolicy(pageUrl,targetUrl){var page,target;try{page=new URL(pageUrl);target=new URL(targetUrl)}catch(e){return {allowed:false,reason:'invalid_url'}}if(!['http:','https:'].includes(target.protocol)||!isPrivateHost(target.hostname))return {allowed:false,reason:'target_not_local'};if(page.protocol==='https:'&&target.protocol==='http:')return {allowed:false,reason:'mixed_content'};return {allowed:true,reason:'ok'}}
  function safePluginId(id){id=String(id||'');return /^vst_[A-Za-z0-9]{6,64}$/.test(id)?id:null}
  function canUseBrowser(){return !!(root&&root.document&&root.window===root)}
  function defaultBridgeUrl(){if(!canUseBrowser())return 'http://127.0.0.1:8766';try{if(root.location.protocol==='http:'&&isPrivateHost(root.location.hostname))return root.location.origin}catch(e){}return 'http://127.0.0.1:8766'}
  var state={url:defaultBridgeUrl(),token:'',plugins:[],selected:'',busy:false};
  function load(){try{var x=JSON.parse(localStorage.getItem('mpc-vst-bridge')||'{}');if(x.url)state.url=normalizeBridgeUrl(x.url)}catch(e){}try{state.token=sessionStorage.getItem('mpc-vst-token')||''}catch(e){}}
  function save(){try{localStorage.setItem('mpc-vst-bridge',JSON.stringify({url:state.url}))}catch(e){}try{if(state.token)sessionStorage.setItem('mpc-vst-token',state.token);else sessionStorage.removeItem('mpc-vst-token')}catch(e){}}
  function statusText(t){try{status(t)}catch(e){var n=document.getElementById('status');if(n)n.textContent=t}}
  async function request(path,options){var url=normalizeBridgeUrl(state.url),policy=bridgeRequestPolicy(canUseBrowser()?root.location.href:url,url);if(!policy.allowed){if(policy.reason==='mixed_content')throw new Error('Depuis la version HTTPS, utilise l’adresse HTTPS LAN affichée par le VST Bridge ou ouvre MPC Studio directement depuis ce Bridge.');throw new Error('Adresse VST locale non autorisée')}var opt=Object.assign({},options||{});opt.headers=Object.assign({},opt.headers||{},state.token?{'X-MPC-Token':state.token}:{});var r=await fetch(url+path,opt);var ct=r.headers.get('content-type')||'';if(!r.ok){var msg='HTTP '+r.status;try{if(ct.includes('json')){var d=await r.json();msg=d.error||msg}}catch(e){}throw new Error(msg)}return r}
  async function refresh(){state.url=normalizeBridgeUrl(document.getElementById('vstBridgeUrl').value);state.token=document.getElementById('vstBridgeToken').value.trim();save();state.busy=true;render();try{var r=await request('/api/vst/plugins'),d=await r.json();state.plugins=Array.isArray(d.plugins)?d.plugins:[];if(!state.plugins.some(function(p){return p.id===state.selected}))state.selected=state.plugins[0]&&state.plugins[0].id||'';render();statusText(state.plugins.length+' VST3 détecté(s) sur le PC')}catch(e){state.plugins=[];render(e.message);statusText('VST Bridge : '+e.message)}finally{state.busy=false;render()}}
  async function processSelected(){if(state.busy)return;var id=safePluginId(state.selected);if(!id)return statusText('Sélectionne un VST3');var p;try{p=selected();await ensureEditableSample(p)}catch(e){return statusText('VST : '+e.message)}state.busy=true;render('Traitement VST3 en cours…');try{var wav=new Blob([audioBufferToWav(p.buffer)],{type:'audio/wav'}),name=encodeURIComponent((p.name||p.id)+'.wav'),r=await request('/api/vst/process?plugin='+encodeURIComponent(id)+'&filename='+name,{method:'POST',headers:{'Content-Type':'audio/wav'},body:wav}),blob=await r.blob(),buffer=await decodeBlob(blob);p.buffer=buffer;p.userBlob=new File([blob],(p.name||'sample')+'-VST.wav',{type:'audio/wav'});p.sample={kind:'user'};p.start=0;p.end=1;p.cloudPath=null;p.externalMeta=Object.assign({},p.externalMeta||{},{provider:'VST Bridge',pluginId:id,processed:true});renderEditor();renderPads();statusText('VST3 appliqué sur '+p.id)}catch(e){statusText('VST : '+e.message);render(e.message)}finally{state.busy=false;render()}}
  function ensureDialog(){var d=document.getElementById('vstDialog');if(d)return d;d=document.createElement('dialog');d.id='vstDialog';d.innerHTML='<div class="vstCard"><div class="dialogHead"><div><small>VST3 PC BRIDGE</small><h2>Plugins Windows sur MPC Studio</h2></div><button id="vstClose" type="button">✕</button></div><p>Pour utiliser les VST3 sans blocage navigateur, lance le pont sur le PC puis ouvre MPC Studio avec l’adresse locale qu’il affiche. Les plugins restent exécutés uniquement sur le PC.</p><label>ADRESSE DU PONT (HTTPS RECOMMANDÉ)<input id="vstBridgeUrl" value=""></label><label>JETON DE SESSION<input id="vstBridgeToken" type="password" autocomplete="off" maxlength="96"></label><button id="vstRefresh" type="button">DÉTECTER LES VST3</button><label>PLUGIN<select id="vstPlugin"></select></label><button id="vstProcess" class="vstPrimary" type="button">APPLIQUER AU PAD SÉLECTIONNÉ</button><div id="vstState" class="vstState">Pont PC non connecté</div><small>Le gestionnaire MeldaProduction sert uniquement à installer les VST3 sur Windows ; il n’est jamais exécuté par la PWA.</small></div>';document.body.appendChild(d);document.getElementById('vstClose').onclick=function(){if(!state.busy)d.close()};document.getElementById('vstRefresh').onclick=refresh;document.getElementById('vstProcess').onclick=processSelected;document.getElementById('vstPlugin').onchange=function(){state.selected=this.value};return d}
  function render(message){if(!canUseBrowser())return;var d=document.getElementById('vstDialog');if(!d)return;var url=document.getElementById('vstBridgeUrl'),token=document.getElementById('vstBridgeToken'),sel=document.getElementById('vstPlugin'),go=document.getElementById('vstProcess'),out=document.getElementById('vstState');if(url&&document.activeElement!==url)url.value=state.url;if(token&&document.activeElement!==token)token.value=state.token;if(sel){sel.innerHTML='';state.plugins.forEach(function(p){sel.add(new Option(p.name||p.id,p.id))});sel.value=state.selected}if(go)go.disabled=state.busy||!state.selected;if(out)out.textContent=message||(state.busy?'Traitement…':state.plugins.length?(state.plugins.length+' plugin(s) prêt(s)'):'Pont PC non connecté')}
  function open(){var d=ensureDialog();render();if(!d.open)d.showModal()}
  function inject(){var g=document.querySelector('.creationGrid');if(g&&!document.getElementById('vstOpenBtn')){var b=document.createElement('button');b.id='vstOpenBtn';b.type='button';b.textContent='🎛 VST3 PC';b.onclick=open;g.appendChild(b)}return !!g}
  function init(){load();var n=0,t=setInterval(function(){n++;if(inject()||n>100)clearInterval(t)},50)}
  if(canUseBrowser()){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}
  return {isPrivateHost:isPrivateHost,normalizeBridgeUrl:normalizeBridgeUrl,bridgeRequestPolicy:bridgeRequestPolicy,safePluginId:safePluginId,open:open,refresh:refresh,processSelected:processSelected};
});
